# -*- coding: utf-8 -*-
"""Workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnA1QFPFCZQKK2C4OicijSNMqVbCKCgE

Exercises on loop
Display Fibonacci series up to 10 terms.
"""

# Fibonacci series up to 10 terms

n = 10
a = 0
b = 1

print("Fibonacci Series:")

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

"""Find the factorial of a given number. Ask the user to provide the number.

"""

# Factorial program

num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers")
elif num == 0:
    print("Factorial of 0 is 1")
else:
    for i in range(1, num + 1):
        factorial *= i
    print("Factorial of", num, "is", factorial)

"""Print a Right Angle Triangle Using For Loop"""

# Right angle triangle pattern

rows = 5

for i in range(1, rows + 1):
    print("*" * i)

"""Exercise on Functions

Simple Calculator Using Functions
"""

2
# Calculator functions

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b


# User input
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operation = input("Enter operation (+, -, *, /): ")

if operation == "+":
    print("Result:", add(num1, num2))
elif operation == "-":
    print("Result:", subtract(num1, num2))
elif operation == "*":
    print("Result:", multiply(num1, num2))
elif operation == "/":
    print("Result:", divide(num1, num2))
else:
    print("Invalid operation")

"""Exercise on Lists and Dictionaries

Remove the First Duplicate Element from a List
"""

# Remove first duplicate

my_list = [1, 2, 3, 2, 4, 5]

seen = set()

for item in my_list:
    if item in seen:
        my_list.remove(item)
        break
    seen.add(item)

print("Updated List:", my_list)

"""Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary.
sample_dict = { "name": "Anderson", "age": 35, "salary": 5000, "city": "London"}
keys = ["name", "salary"]
"""

sample_dict = {
    "name": "Anderson",
    "age": 35,
    "salary": 5000,
    "city": "London"
}

keys = ["name", "salary"]

new_dict = {k: sample_dict[k] for k in keys}

print("New Dictionary:", new_dict)

"""Write a Python program to convert two lists into a dictionary in a way that item from list_one is the key and item from list_two is the value.
list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]
"""

list_one = ["name", "age", "city"]
list_two = ["John", 25, "New York"]

result = dict(zip(list_one, list_two))

print("Converted Dictionary:", result)

"""examples"""

# Taking input from the user
first_name = input("Please enter your first name: ")

# Displaying the output
print("Hello,", first_name + "! Welcome to Python Lab.")

"""control structures"""

# Taking integer input from the user
value = int(input("Please enter a number: "))  # input() returns string, so we convert it using int()

# Checking the condition
if value < 0:
    print("The number is negative")
elif value == 0:
    print("The number is zero")
else:
    print("The number is positive")

"""Loop"""

#whileloop

total = 0
counter = 1

while counter <= 10:   # Stopping condition
    total = total + counter   # Add current value to total
    counter += 1   # Increment counter

print("Sum using while loop:", total)

#for loop
total = 0

for counter in range(1, 11):   # range(start, stop) where stop is excluded
    total = total + counter

print("Sum using for loop:", total)

"""List Modification"""

first_list = [1, 2, 3, 8]
print("The list is:", first_list)

print("First value of the list is:", first_list[0])
print("Last value of the list is:", first_list[-1])

for value in first_list:
    print(value)

"""Other List Operations"""

# Original list
first_list = [1, 2, 3, 8]
print("Original List:", first_list)

# 1️⃣ Append – adds element at the end of the list
first_list.append(10)
print("After appending 10:", first_list)

# 2️⃣ Modify – change element using index
first_list[2] = 5   # Changing the third element (index 2)
print("After modifying the third element:", first_list)

# 3️⃣ Insert – insert element at a specific position
first_list.insert(2, 12)   # Insert 12 at index 2 (third position)
print("After inserting 12 at third position:", first_list)

"""Dictionary Modification"""

zipCode = {'London': 290, 'Leeds': 578, 'Wolverhampton': 911}

print("Original Dictionary:")

for key in zipCode:
    print(key, "=", zipCode[key])

key_list = zipCode.keys()
value_list = zipCode.values()

print("Keys:", key_list)
print("Values:", value_list)

zipCode['London'] = 666

print("After modifying London value:")

for key in zipCode:
    print(key, "=", zipCode[key])

zipCode['Birmingham'] = 111

print("After adding Birmingham:")

for key in zipCode:
    print(key, "=", zipCode[key])

"""Functions"""

def oddEven(num):
    if num % 2 == 0:
        print("The number is even")
    else:
        print("The number is odd")


# Taking input from the user
num = int(input("Please enter a number: "))

# Calling the function
oddEven(num)

